# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5b228a6818ff0d9d3df49e4dd09b9297eedf3e55091590be5b0857d178a082b2c5fe112ac629f2ef5db085b1d620c4c4f07c19f963353d2467190edd263bb182

test:
  secret_key_base: 840053afff994ff9bbe5d24ee70246ccf2f720401bf3bc25cfec0a8c345aadd36d6d68f79ceab9abc14deeaae6f453f1796d3a5437f7e724d3f15169e51d02b7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
